[book]
authors = ["Bas Bossink <bas.bossink@gmail.com>"]
multilingual = false
src = "src"
title = "Buddha inspired software development"
description = "A look at software development through the lens of the teachings of the Mr. Gotama."

[build]
create-missing = true
